FROM  solr:6.6-alpine

#build with:
#maven build

#start on development with:
#docker run --net=cora -p 8984:8983 --name solr  -d  -P solr solr-create -c coracore


#start on build server with:
#docker run --net=cora-test  --name solr-test -d  solr -P solr solr-create -c coracore

#start on external with:
#docker run --net=cora  --name solr  -d  solr -P solr solr-create -c coracore

#reomove unused volumes with:
#docker volume rm $(docker volume ls -q)